# Base configs
# baseurl: "http:/127.0.0.1:4000"
# baseurl: "http://photography.tegongdete.cn"
imgae_url : "http://qiniu.tegongdete.cn/"
image_thumbs_prefix: "thumb-"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by tegongdete"
subtitle: "To Record Life"
author: "Tegongdete"
header:
 title: "Photography"
 subtitle: "by tegongdete"
footer:
 name: "Hey there, my name is Wang Yijie"
 bio: "I am a developer and this site is used for learning photography."
#  github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  # facebook: "https://www.facebook.com/ramswaroop"
  # twitter: "https://www.twitter.com/ram__patra"
  # instagram: "https://www.instagram.com/ram_patra"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/wyj1026"
